#!/usr/bin/env bash
## env
set -ex
## Check ENV
[[ ! "$BUILD_DEPENDENCY_BENCHER_DIR" ]]&& BUILD_DEPENDENCY_BENCHER_DIR=$HOME/mango_bencher
#[[ ! "$BUILD_DEPENDENCY_SOLALNA_DOWNLOAD_DIR" ]]&& BUILD_DEPENDENCY_SOLALNA_DOWNLOAD_DIR=$HOME/mango_bencher/deps
[[ ! "$SOLANA_BUILD_BRANCH" ]]&&[[ ! "$SOLANA_GIT_COMMIT" ]]&& echo No SOLANA_BUILD_BRANCH or SOLANA_GIT_COMMIT > env.output && exit 1
[[ ! "$SOLANA_REPO" ]]&& echo no SOLANA_REPO=$SOLANA_REPO&& exit 1
[[ ! "$MANGO_BENCHER_REPO" ]]&&  echo no MANGO_BENCHER_REPO=$MANGO_BENCHER_REPO&& exit 1
[[ ! "$MANGO_BENCHER_BRANCH" ]]&&  echo no MANGO_BENCHER_BRANCH=$MANGO_BENCHER_BRANCH&& exit 1
[[ ! "$ACCOUNTS" ]]&&  echo no ACCOUNTS=$ACCOUNTS&& exit 1
[[ ! "$AUTHORITY_FILE" ]] &&  echo no AUTHORITY_FILE=$AUTHORITY_FILE&& exit 1
[[ ! "$ID_FILE" ]] &&  echo no ID_FILE=$ID_FILE&& exit 1
[[ ! "$CHANNEL" ]]&& CHANNEL=stable && echo No CHANNEL , use $CHANNEL
[[ ! "$RUST_VER" ]]&& RUST_VER=default && echo No RUST_VER use $RUST_VER 

# Printout Env
[[ -f "env.output" ]]&& rm env.output
echo BUILD_MANGO_BENCHER: $BUILD_MANGO_BENCHER >> env.output
echo BUILD_DEPENDENCY_BENCHER_DIR: $BUILD_DEPENDENCY_BENCHER_DIR >> env.output
#echo BUILD_DEPENDENCY_SOLALNA_DOWNLOAD_DIR: $BUILD_DEPENDENCY_SOLALNA_DOWNLOAD_DIR >> env.output
echo SOLANA_BUILD_BRANCH: $SOLANA_BUILD_BRANCH >> env.output
echo SOLANA_GIT_COMMIT: $SOLANA_GIT_COMMIT >> env.output
echo SOLANA_REPO: $SOLANA_REPO >> env.output
echo MANGO_BENCHER_REPO: $MANGO_BENCHER_REPO >> env.output
echo MANGO_BENCHER_BRANCH: $MANGO_BENCHER_BRANCH >> env.output
echo ACCOUNTS: $ACCOUNTS >> env.output
echo AUTHORITY_FILE: $AUTHORITY_FILE >> env.output
echo ID_FILE: $ID_FILE >> env.output
echo CHANNEL: $CHANNEL >> env.output
echo RUST_VER: $RUST_VER >> env.output

## Download key files from gsutil
download_file() {
	for retry in 0 1
	do
		if [[ $retry -gt 1 ]];then
			break
		fi
		gsutil cp  gs://mango_bencher-dos/$1 ./
		if [[ ! -f "$1" ]];then
			echo "NO $1 found, retry"
		else
			break
		fi
	done
}
upload_file() {
	gsutil cp  $1 gs://mango_bencher-dos/$2
}
## preventing lock-file build fail, 
## also need to disable software upgrade in image
sudo fuser -vki -TERM /var/lib/dpkg/lock /var/lib/dpkg/lock-frontend || true
sudo dpkg --configure -a
sudo apt update
## pre-install and rust version
sudo apt-get install -y libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang cmake make libprotobuf-dev protobuf-compiler
rustup default stable
rustup update

cd $HOME
[[ -d "$BUILD_DEPENDENCY_BENCHER_DIR" ]]&& rm -rf mango_bencher
# clone mango_bencher and mkdir dep dir
git clone $MANGO_BENCHER_REPO
#if [[ -d "$BUILD_DEPENDENCY_BENCHER_DIR" ]];then
#    mkdir $BUILD_DEPENDENCY_SOLALNA_DOWNLOAD_DIR
#else
#    exit 1
#fi

cd $BUILD_DEPENDENCY_BENCHER_DIR
#git submodule update --init --recursive
#if [[ "$BUILD_MANGO_BENCHER" == "true" ]];then
#	# build solana b4 build mango
#	cd $BUILD_DEPENDENCY_SOLALNA_DOWNLOAD_DIR
#	git clone $SOLANA_REPO
#	cd $BUILD_DEPENDENCY_SOLALNA_DOWNLOAD_DIR/solana
#	if [[ "$SOLANA_GIT_COMMIT" ]];then
#		git checkout $SOLANA_GIT_COMMIT
#	elif [[ "$SOLANA_BUILD_BRANCH" ]];then
#		git checkout $SOLANA_BUILD_BRANCH
#	else 
#		exit 1
#	fi
#	git branch || true
#	# move to mango_bencher and build mango_bencher
#	cd $BUILD_DEPENDENCY_BENCHER_DIR
#fi

if  [[ "$BUILD_MANGO_BENCHER" == "true" ]];then
	cargo build --release
	# cp from BUILD_DEPENDENCY_BENCHER_DIR to HOME
	cp $BUILD_DEPENDENCY_BENCHER_DIR/target/release/solana-bench-mango $HOME
	chmod +x $HOME/solana-bench-mango
else
	# download from bucket
	cd $HOME
	download_file solana-bench-mango
	[[ ! -f "$HOME/solana-bench-mango" ]] && echo no solana-bench-mango downloaded && exit 1
fi

# pre-requicy by configure_mango
cd $HOME
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g typescript
sudo npm install -g ts-node
sudo npm install -g yarn
# download configure_mango repo
git clone $MANGO_CONFIGURE_REPO
cd $BUILD_DEPENDENCY_CONFIGUERE_DIR
# warning package-lock.json found. 
# Your project contains lock files generated by tools other than Yarn. 
# It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files.
# To clear this warning, remove package-lock.json.
# Memo by author: use yarn instead of npm install
rm package-lock.json || true
git checkout $MANGO_CONFIGURE_BRANCH
yarn install && yarn add @blockworks-foundation/mango-client

echo --- stage: Start To Download Files
cd $BUILD_DEPENDENCY_CONFIGUERE_DIR
download_file $AUTHORITY_FILE
[[ ! -f "$AUTHORITY_FILE" ]]&&echo no $AUTHORITY_FILE file && exit 1
cp $AUTHORITY_FILE $HOME
download_file $ID_FILE
[[ ! -f "$ID_FILE" ]]&&echo no $ID_FILE file && exit 1
cp $ID_FILE $HOME

cd $BUILD_DEPENDENCY_BENCHER_DIR
echo $ACCOUNTS
download_accounts=( $ACCOUNTS )
for acct in ${download_accounts[@]}
do
  echo --- start to download $acct
  download_file $acct
  cp $acct $HOME
done

echo --- stage: Start refunding clients accounts
cd $BUILD_DEPENDENCY_CONFIGUERE_DIR
for acct in ${download_accounts[@]}
do
  ts-node refund_users.ts "${HOME}/$acct" > out.log 2>1 || true
  if [ $? -ne 0 ]; then
    echo --- refund failed for $acct
    cat out.log
  fi
done

cd $HOME 
download_file dos-metrics-env.sh
[[ ! -f "$HOME/dos-metrics-env.sh" ]]&&echo no dos-metrics-env.sh file && exit 1
download_file dos-report-env.sh
[[ ! -f "$HOME/dos-report-env.sh" ]]&&echo no dos-report-env.sh file && exit 1

upload_file $BUILD_DEPENDENCY_BENCHER_DIR/target/release/solana-bench-mango
